### ISSUE TITLE
miss googlesearch lib

### ISSUE THREAD

**Issue by blackout314** [woj-ciech/pepe#1]
```
$ python pepe.py
Traceback (most recent call last):
  File "pepe.py", line 5, in <module>
    import Utilsy
  File "/xxx/xxx/xxx/xxx/pepe/Utilsy.py", line 11, in <module>
    from googlesearch import search
ImportError: cannot import name search
```

```
Python 3.6.5 (default, Mar 30 2018, 06:41:49)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
```

**Comment by secjo** [comment]
Same issue!

**Comment by laurianops** [comment]
What system have you used @blackout314 ?
and you @eriksss ?

**Comment by secjo** [comment]
MacOS

**Comment by laurianops** [comment]
sorry, i use Fedora . but, i going to try to install it's today ..

**Comment by blackout314** [comment]
> MacOS

me too

**Comment by jeretc** [comment]
sudo pip3 install "packagename"
----
search-google
python-pushsafer
piplapis-python
fullcontact.py / https://github.com/fullcontact/fullcontact.py
elasticsearch
pyhibp
validate_email
----
python3 pepe.py -h
