### ISSUE TITLE
ImportError: cannot import name search

### ISSUE THREAD

**Issue by jepunband** [woj-ciech/pepe#2]
└──╼ $sudo python pepe.py -h
Traceback (most recent call last):
  File "pepe.py", line 5, in <module>
    import Utilsy
  File "/home/drake/apps/pepe/Utilsy.py", line 11, in <module>
    from googlesearch import search
ImportError: cannot import name search

**Comment by jeretc** [comment]
sudo pip3 install "packagename"
----
search-google
python-pushsafer
piplapis-python
fullcontact.py / https://github.com/fullcontact/fullcontact.py
elasticsearch
pyhibp
validate_email
----
python3 pepe.py -h
